openapi: 3.2.0
info:
  title: Transmit SMS Keywords API
  description: '<p>With so many SMS APIs on the market today, you might think that they all do the same thing: send text messages. But with our flexible and powerful suite of APIs, you can do more than that.</p>'
  version: 1.0.0
servers:
- url: https://api.transmitsms.com
tags:
- name: Keywords
paths:
  /add-keyword.json:
    post:
      tags:
      - Keywords
      summary: Add Keyword
      description: Add New Keyword
      security:
      - basicAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - keyword
              - number
              properties:
                keyword:
                  type: string
                  description: The first word of a text message
                  example: example
                number:
                  type: integer
                  description: The dedicated virtual number that the keyword belongs to
                  example: 1234567890
                reference:
                  type: string
                  description: Your own reference (up to 100 characters)
                  example: reference123
                list_id:
                  type: integer
                  description: ID of a list to add respondents to, list ID's can be found in the title of a list or in the list page URL
                  example: 987654321
                welcome_message:
                  type: string
                  description: SMS message to send to new members
                  example: Welcome to our service!
                members_message:
                  type: string
                  description: SMS message to existing members
                  example: Welcome back!
                activate:
                  type: boolean
                  description: Whether to make the keyword active immediately.
                  default: true
                forward_url:
                  type: string
                  format: url
                  description: Forward messages to a URL
                forward_email:
                  type: string
                  format: email
                  description: Forward messages to a set of email addresses
                forward_sms:
                  type: integer
                  description: Forward messages to a set of MSISDNs
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  keyword:
                    type: string
                    example: NEWS
                  reference:
                    type: string
                    example: Gym news
                  number:
                    type: integer
                    example: 61418279031
                  list_id:
                    type: integer
                    example: 4214634
                  welcome_message:
                    type: string
                    example: Welcome to Mike's gym news
                  member_message:
                    type: string
                    example: Thanks for your continued support
                  forward_url:
                    type: string
                    example: http://example.com/gym-promo
                  forward_sms:
                    type: string
                    example: 61491570157,61491570158
                  forward_email:
                    type: string
                    example: news@example.com,mike@example.com
                  status:
                    type: string
                    example: open
                  billing_date:
                    type: string
                    format: date
                    example: '2020-07-24'
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: SUCCESS
                      description:
                        type: string
                        example: OK
              example:
                keyword: NEWS
                reference: Gym news
                number: 61418279031
                list_id: 4214634
                welcome_message: Welcome to Mike's gym news
                member_message: Thanks for your continued support
                forward_url: http://example.com/gym-promo
                forward_sms: 61491570157,61491570158
                forward_email: news@example.com,mike@example.com
                status: open
                billing_date: '2020-07-24'
                error:
                  code: SUCCESS
                  description: OK
            text/plain:
              schema:
                type: string
              example: "<?xml version=\"1.0\"?>\n<response>\n    <keyword>GYM</keyword>\n    <reference>Gym news</reference>\n    <number>61418279031</number>\n    <list_id>4214637</list_id>\n    <welcome_message>Welcome to Mike's gym news</welcome_message>\n    <member_message>Thanks for your continued support</member_message>\n    <forward_url>http://example.com/gym-promo</forward_url>\n    <forward_sms>61491570157,61491570158</forward_sms>\n    <forward_email>news@example.com,mike@example.com</forward_email>\n    <status>open</status>\n    <billing_date>2020-07-24</billing_date>\n    <error>\n        <code>SUCCESS</code>\n        <description>OK</description>\n    </error>\n</response>"
  /edit-keyword.json:
    post:
      tags:
      - Keywords
      summary: Edit Keyword
      description: Edit an existing keyword.
      security:
      - basicAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - keyword
              - number
              properties:
                keyword:
                  type: string
                  description: The first word of a text message.
                  example: keyword
                number:
                  type: integer
                  description: The dedicated virtual number that the keyword belongs to.
                  example: 123456789
                reference:
                  type: string
                  description: Your own reference (up to 100 characters).
                  example: reference
                status:
                  type: string
                  description: 'Open, will set the Keyword to being active. Closed, will close the Keyword.

                    '
                  enum:
                  - Open
                  - Closed
                list_id:
                  type: integer
                  description: ID of a list to add respondents to. List ID's can be found in the title of a list or in the list page URL.
                  example: 987654321
                welcome_message:
                  type: string
                  description: SMS message to send to new members.
                  example: Welcome to our service!
                members_message:
                  type: string
                  description: SMS message to existing members.
                  example: Welcome back!
                activate:
                  type: boolean
                  description: Whether to make the keyword active immediately.
                  default: true
                forward_url:
                  type: string
                  format: uri
                  description: Forward messages to a URL.
                  example: http://example.com/forward
                forward_email:
                  type: string
                  format: email
                  description: Forward messages to a set of email addresses.
                  example: example@example.com
                forward_sms:
                  type: array
                  items:
                    type: integer
                  description: Forward messages to a set of msisdns.
                  example:
                  - 123456789
                  - 987654321
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  keyword:
                    type: string
                    example: NEWS
                    description: The keyword.
                  reference:
                    type: string
                    example: Gym news
                    description: Your own reference.
                  number:
                    type: integer
                    example: 61418279031
                    description: The dedicated virtual number.
                  list_id:
                    type: integer
                    example: 4214634
                    description: ID of the list.
                  welcome_message:
                    type: string
                    example: Welcome to Fitness gym news
                    description: SMS message to send to new members.
                  member_message:
                    type: string
                    example: Thanks for your continued support
                    description: SMS message to existing members.
                  forward_url:
                    type: string
                    format: uri
                    example: http://example.com/gym-promo
                    description: Forward messages to a URL.
                  forward_sms:
                    type: string
                    example: 61491570157,61491570158
                    description: Forward messages to a set of MSISDNs.
                  forward_email:
                    type: string
                    example: news@example.com,mike@example.com
                    description: Forward messages to a set of email addresses.
                  status:
                    type: string
                    example: open
                    description: Status of the response.
                  billing_date:
                    type: string
                    format: date
                    example: '2020-07-24'
                    description: Date of billing.
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: SUCCESS
                        description: Error code.
                      description:
                        type: string
                        example: OK
                        description: Error description.
              example:
                keyword: NEWS
                reference: Gym news
                number: 61418279031
                list_id: 4214634
                welcome_message: Welcome to Fitness gym news
                member_message: Thanks for your continued support
                forward_url: http://example.com/gym-promo
                forward_sms: 61491570157,61491570158
                forward_email: news@example.com,mike@example.com
                status: open
                billing_date: '2020-07-24'
                error:
                  code: SUCCESS
                  description: OK
            text/plain:
              schema:
                type: string
              example: "<?xml version=\"1.0\"?>\n<response>\n    <keyword>NEWS</keyword>\n    <reference>Gym news</reference>\n    <number>61418279031</number>\n    <list_id>4214634</list_id>\n    <welcome_message>Welcome to Fitness gym news</welcome_message>\n    <member_message>Thanks for your continued support</member_message>\n    <forward_url>http://example.com/gym-promo</forward_url>\n    <forward_sms>61491570157,61491570158</forward_sms>\n    <forward_email>news@example.com,mike@example.com</forward_email>\n    <status>open</status>\n    <billing_date>2020-07-24</billing_date>\n    <error>\n        <code>SUCCESS</code>\n        <description>OK</description>\n    </error>\n</response>"
  /get-keywords.json:
    post:
      tags:
      - Keywords
      summary: Get Keywords
      description: Get a list of existing keywords.
      security:
      - basicAuth: []
      requestBody:
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                number:
                  type: integer
                  description: Filter the list by virtual number.
                  example: 61418279031
                page:
                  type: integer
                  description: Page number for pagination.
                  example: 1
                max:
                  type: integer
                  description: Maximum results returned per page.
                  example: 5
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: object
                    properties:
                      count:
                        type: integer
                        description: Total count of keywords returned in the current page.
                      number:
                        type: integer
                        description: Current page number.
                  keywords_total:
                    type: integer
                    description: Total count of keywords available.
                  keywords:
                    type: array
                    items:
                      type: object
                      properties:
                        keyword:
                          type: string
                          description: The keyword.
                        reference:
                          type: string
                          description: Reference for the keyword.
                        number:
                          type: integer
                          description: The dedicated virtual number associated with the keyword.
                        list_id:
                          type: integer
                          description: ID of the list associated with the keyword.
                        welcome_message:
                          type: string
                          description: SMS message sent to new members.
                        member_message:
                          type: string
                          description: SMS message sent to existing members.
                        forward_url:
                          type: string
                          format: uri
                          description: URL to forward messages.
                        forward_sms:
                          type: string
                          description: MSISDNs to forward messages to.
                        forward_email:
                          type: string
                          description: Email addresses to forward messages to.
                        status:
                          type: string
                          description: Status of the keyword.
                        billing_date:
                          type: string
                          format: date
                          description: Billing date associated with the keyword.
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        description: Error code.
                      description:
                        type: string
                        description: Description of the error.
              example:
                page:
                  count: 1
                  number: 1
                keywords_total: 2
                keywords:
                - keyword: GYM
                  reference: Gym news
                  number: 61418279031
                  list_id: 4214637
                  welcome_message: Welcome to Mike's gym news
                  member_message: Thanks for your continued support
                  forward_url: http://example.com/gym-promo
                  forward_sms: 61491570157,61491570158
                  forward_email: news@example.com,mike@example.com
                  status: open
                  billing_date: '2020-07-24'
                - keyword: NEWS
                  reference: Gym news
                  number: 61418279031
                  list_id: 4214634
                  welcome_message: Welcome to Mike's gym news
                  member_message: Thanks for your continued support
                  forward_url: http://example.com/gym-promo
                  forward_sms: 61491570157,61491570158
                  forward_email: news@example.com,mike@example.com
                  status: open
                  billing_date: '2020-07-24'
                error:
                  code: SUCCESS
                  description: OK
            text/plain:
              schema:
                type: string
              example: "<?xml version=\"1.0\"?>\n<response>\n    <page>\n        <count>1</count>\n        <number>1</number>\n    </page>\n    <keywords_total>2</keywords_total>\n    <keywords>\n        <item>\n            <keyword>GYM</keyword>\n            <reference>Gym news</reference>\n            <number>61418279031</number>\n            <list_id>4214637</list_id>\n            <welcome_message>Welcome to Mike's gym news</welcome_message>\n            <member_message>Thanks for your continued support</member_message>\n            <forward_url>http://example.com/gym-promo</forward_url>\n            <forward_sms>61491570157,61491570158</forward_sms>\n            <forward_email>news@example.com,mike@example.com</forward_email>\n            <status>open</status>\n            <billing_date>2020-07-24</billing_date>\n        </item>\n        <item>\n            <keyword>NEWS</keyword>\n            <reference>Gym news</reference>\n            <number>61418279031</number>\n            <list_id>4214634</list_id>\n            <welcome_message>Welcome to Mike's gym news</welcome_message>\n            <member_message>Thanks for your continued support</member_message>\n            <forward_url>http://example.com/gym-promo</forward_url>\n            <forward_sms>61491570157,61491570158</forward_sms>\n            <forward_email>news@example.com,mike@example.com</forward_email>\n            <status>open</status>\n            <billing_date>2020-07-24</billing_date>\n        </item>\n    </keywords>\n    <error>\n        <code>SUCCESS</code>\n        <description>OK</description>\n    </error>\n</response>"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: 'Use the `Authorization` header with the value `Basic {base64(api_key:api_secret)}`.

        - `api_key`: Your API key

        - `api_secret`: Your API secret

        '
